package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List<String> _jspx_dependants;

  private org.glassfish.jsp.api.ResourceInjector _jspx_resourceInjector;

  public java.util.List<String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;

    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;
      _jspx_resourceInjector = (org.glassfish.jsp.api.ResourceInjector) application.getAttribute("com.sun.appserv.jsp.resource.injector");

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>no nico</title>\n");
      out.write("        <meta property=\"og:image\" name=\"image\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>Say No to Nicotine</title>\n");
      out.write("    <link rel=\"icon\" href=\"./no_nicotine.jpg\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("         body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            background-color: #f4f4f4;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Header */\n");
      out.write("        header {\n");
      out.write("            text-align: center;\n");
      out.write("            background-color: #fb860a;\n");
      out.write("            color: white;\n");
      out.write("            padding: 20px;\n");
      out.write("            font-size: 28px;\n");
      out.write("            font-weight: bold;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Navbar */\n");
      out.write("        .navbar {\n");
      out.write("            background-color: black;\n");
      out.write("            border: none;\n");
      out.write("        }\n");
      out.write("        .navbar-brand {\n");
      out.write("            color: white !important;\n");
      out.write("            font-size: 20px;\n");
      out.write("        }\n");
      out.write("        .navbar-nav > li > a {\n");
      out.write("            color: white !important;\n");
      out.write("        }\n");
      out.write("        .navbar-nav .dropdown-menu {\n");
      out.write("            background-color: black;\n");
      out.write("        }\n");
      out.write("        .navbar-nav .dropdown-menu a {\n");
      out.write("            color: white !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Hero Section */\n");
      out.write("        .hero {\n");
      out.write("            background: url(\"back.jpg\") no-repeat center center/cover;\n");
      out.write("            color: white;\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 100px 20px;\n");
      out.write("        }\n");
      out.write("        .hero h1 {\n");
      out.write("            font-size: 36px;\n");
      out.write("            font-weight: bold;\n");
      out.write("        }\n");
      out.write("        .hero p {\n");
      out.write("            font-size: 18px;\n");
      out.write("            margin: 20px 0;\n");
      out.write("        }\n");
      out.write("        .hero .btn {\n");
      out.write("            background: #fb860a;\n");
      out.write("            color: white;\n");
      out.write("            padding: 15px 30px;\n");
      out.write("            font-size: 18px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("        }\n");
      out.write("        .hero .btn:hover {\n");
      out.write("            background: #e67e22;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Carousel */\n");
      out.write("        .carousel-container {\n");
      out.write("            max-width: 500px;\n");
      out.write("            margin: 30px auto;\n");
      out.write("            background: white;\n");
      out.write("            padding: 10px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        .carousel-inner {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center; /* Centers images vertically */\n");
      out.write("            justify-content: center; /* Centers images horizontally */\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        .carousel-inner img {\n");
      out.write("            width: auto;\n");
      out.write("            max-width: 100%;\n");
      out.write("            height: 300px;\n");
      out.write("            object-fit: cover;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            border-radius: 10px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* About Section */\n");
      out.write("        .about, .services, .contact {\n");
      out.write("            padding: 60px 20px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Contact Section */\n");
      out.write("        .contact-form {\n");
      out.write("            background: white;\n");
      out.write("            padding: 20px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("            max-width: 600px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("        input, textarea {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 10px;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("            border: 1px solid #ccc;\n");
      out.write("            border-radius: 5px;\n");
      out.write("        }\n");
      out.write("        textarea {\n");
      out.write("            resize: vertical;\n");
      out.write("            height: 100px;\n");
      out.write("        }\n");
      out.write("        button {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 10px;\n");
      out.write("            background: #007bff;\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            font-size: 16px;\n");
      out.write("        }\n");
      out.write("        button:hover {\n");
      out.write("            background: #0056b3;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Footer */\n");
      out.write("        footer {\n");
      out.write("            background-color: black;\n");
      out.write("            color: white;\n");
      out.write("            text-align: center;\n");
      out.write("            padding: 15px;\n");
      out.write("            margin-top: 30px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        \n");
      out.write("    <header>\n");
      out.write("        Say No to Nicotine\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <!-- Navbar -->\n");
      out.write("    <nav class=\"navbar navbar-inverse\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">Recovery Center</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("                <ul class=\"nav navbar-nav\">\n");
      out.write("                    <li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("                    <li><a href=\"#\">About</a></li>\n");
      out.write("                    <li><a href=\"#\">Events</a></li>\n");
      out.write("                    <li><a href=\"#\">Contact</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                    <li class=\"dropdown\">\n");
      out.write("                        <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Register\n");
      out.write("                            <span class=\"caret\"></span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                            <li><a href=\"./docreg.jsp\">Doctor</a></li>\n");
      out.write("                            <li><a href=\"./visireg.jsp\">Visitor</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"dropdown\">\n");
      out.write("                        <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Login\n");
      out.write("                            <span class=\"caret\"></span>\n");
      out.write("                        </a>\n");
      out.write("                        <ul class=\"dropdown-menu\">\n");
      out.write("                            <li><a href=\"./admin.jsp\">Admin</a></li>\n");
      out.write("                            <li><a href=\"./doctor.jsp\">Doctor</a></li>\n");
      out.write("                            <li><a href=\"./visitor.jsp\">Visitor</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Hero Section -->\n");
      out.write("    <div class=\"hero\">\n");
      out.write("        <h1>Your Journey to a Smoke-Free Life Begins Here</h1>\n");
      out.write("        <p>Join our support network and take the first step towards a healthier future.</p>\n");
      out.write("        <a href=\"#contact\" class=\"btn\">Get Help Now</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Slideshow -->\n");
      out.write("    <div class=\"carousel-container\">\n");
      out.write("        <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("            <div class=\"carousel-inner\">\n");
      out.write("                <div class=\"item active\">\n");
      out.write("                    <img src=\"project1.jpg\" alt=\"Support Image\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"item\">\n");
      out.write("                    <img src=\"project2.jpg\" alt=\"Doctor Therapy\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"item\">\n");
      out.write("                    <img src=\"silde2.jpg\" alt=\"Support Group\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\n");
      out.write("                <span class=\"glyphicon glyphicon-chevron-left\"></span>\n");
      out.write("            </a>\n");
      out.write("            <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\n");
      out.write("                <span class=\"glyphicon glyphicon-chevron-right\"></span>\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- About Section -->\n");
      out.write("    <div class=\"about\">\n");
      out.write("        <h2>About Us</h2>\n");
      out.write("        <p>We provide professional guidance, therapy, and community support to help individuals overcome nicotine addiction.</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Contact Section -->\n");
      out.write("<!--    <div class=\"contact\">\n");
      out.write("        <h2>Contact Us</h2>\n");
      out.write("        <form class=\"contact-form\">\n");
      out.write("            <input type=\"text\" placeholder=\"Your Name\">\n");
      out.write("            <input type=\"email\" placeholder=\"Your Email\">\n");
      out.write("            <textarea placeholder=\"Message\"></textarea>\n");
      out.write("            <button>Send</button>\n");
      out.write("        </form>\n");
      out.write("    </div>-->\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer>&copy; 2025 Say No to Nicotine. All Rights Reserved.</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
